# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 995dc5a2182a52546a2226bd6c9d57727c85fc4736562fbeb8b965cfd873102900496be5320569e780d4879eed6a4a85a5a84f72373e9ee61c73dbdea2cea976

test:
  secret_key_base: 6c8e54b1d4c94a6e6bc284ee1741faf07ebb4698cdfc45f9e9815087a412c5ac573570b51169de93380bf4ba3edc66dcdcf6fcde34821d2ef63fe6525b546e10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
